# Tomcat Server

server:
  port: 8080
  
  
# Logger
logging.level:
  web: DEBUG
  '[com.comit.users]': DEBUG
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: Dubblin080@
